apiVersion: storage.k8s.io/v1
kind: StorageClass

metadata:
  name: sog-managed-disk
  labels:
    app.kubernetes.io/part-of: sog-platform
    sog.io/environment: nonprod

provisioner: disk.csi.azure.com

parameters:
  skuName: StandardSSD_LRS
  tags: "CostCenter=nonproduction,Environment=nonproduction,Owner=platform-team"

reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true