apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

images:
  - name: sogplatformacr.azurecr.io/orders-api
    newName: sogplatformacr.azurecr.io/orders-api
    newTag: bootstrap