output "consumed_nonprod_aks_name" {
  value = data.terraform_remote_state.platform.outputs.nonprod_aks_name
}

output "consumed_shared_acr_login_server" {
  value = data.terraform_remote_state.platform.outputs.shared_acr_login_server
}

output "consumed_nonprod_oidc_issuer_url" {
  value = data.terraform_remote_state.platform.outputs.nonprod_aks_oidc_issuer_url
}

output "workload_contracts" {
  description = "Resolved workload contracts generated by the platform module."

  value = {
    for name, workload in module.workload : name => {
      namespace        = workload.namespace_name
      service          = workload.service_name
      service_account  = workload.service_account_name
      managed_identity = workload.managed_identity_name
      size_profile     = workload.size_profile
    }
  }
}